### PR TITLE
Adding PN532 ISO14443A Emulation Support 

### PR DESCRIPTION
**Pull request by salmg**
These changes will add PN532 emulation support; the PN532 will be able
to act as smart card. I tested in different Arduino versions: Nano, Uno & clones.
Also I tested it in an ESP32 and LoRa boards. So we are going to have fun.

There is no limitation with these changes.

### CODE REVIEW

**Comment by ladyada** [comment]
thanks - we didn't test this code but it doesnt conflict with existing library

**Comment by salmg** [comment]
A pleasure & thanks for your hard work

**Comment by Amitom** [comment]
Hi, @salmg , I'm a newbie in this technology, but while I read the subject of this PR, I though the PN532 would be able to be read by a cellphone as a dumb Card (like a Adafruit 13.56Mhz RFID/NFC Card). Not only by PoS devices.

Did I totally misunderstand the functionality you added ? ^^

Thanks per advance :)

**Comment by salmg** [comment]
Hello @Amitom 

It is more complex than that. You have to create a communication to a terminal, PoS or mobile application which could mimic the terminal role or PCD technology. This communication has to be implemented following the APDU protocol, and the example follows the payment system communication just to start a process and to show an example. 

The functionality that I added is to start the communication from the PN532 as "smart card" or emulation mode instead of reader mode which could be useful to emulate different technologies, not just payment systems.

Because the APDU protocol could be useful for many different technologies, that is why I just added how to read data and how to respond to the device; the users that want to have a complete communication may use this as example to follow the set up process, but they need to develop the communication process following the APDU communication depending of their goals.

**Pull request merged**
