### PR TITLE
Add non blocking SPI functionnalities

### PR DESCRIPTION
**Pull request by Oliv4945**
Hi,

The current library is polling NFC reader until a tag is placed on it. I implemented non blocking functions to use the interrupt from the reader

### CODE REVIEW

**Comment by lefuturiste** [comment]
Hi, this is the exact feature that I'm looking for. Look great but can you provide a exemple of code to use with this new feature ? It will be great! I already started trying to run my code with this feature but I didn't find a way to make the thing working. Thanks for this PR

**Comment by Oliv4945** [comment]
Sure, see it here: https://github.com/Oliv4945/nfcAudio/commits/ndef_url

**Comment by lefuturiste** [comment]
Thanks for your work this code works really great

**Comment by electrek** [comment]
Hi @Oliv4945, it looks like the example link you posted above is broken.  Can you please repost and example?  Thanks!

**Comment by Oliv4945** [comment]
Hi @electrek , I merge the branch in master. It is now [here](https://github.com/Oliv4945/nfcAudio/blob/master/src/main.cpp)

**Comment by waza-ari** [comment]
Any idea why this is not merged yet? Looking exactly for this! Thanks for your work @Oliv4945

**Comment by siddacious** [comment]
@waza-ari this is waiting on testing by a maintainer. @olive4945, please add a usage example to this PR for me or someone else to test and for others to know how to use your work without having to track down another example elsewhere

**Comment by Oliv4945** [comment]
Hey @siddacious, are you from Adafruit? If so, great to here that you are still looking at this board/PR :)

I can create an example but my only board is integrated in a project so I can not test it. @waza-ari or @electrek : anyone to test ?

**Comment by electrek** [comment]
Hi @Oliv4945, if you have an example you can share, I can test it.  Thanks!

**Comment by waza-ari** [comment]
Thank you @electrek. I also have one PN532 board already built into a project. in addition, I switched to I2C, because I was able to implement the power down functionality there quite easily. Thanks for your work nonetheless!

**Comment by Udinic** [comment]
I couldn't get this code to work for me, but it inspired me to create a similar solution for I2C. I added a few methods and a working example, including a wiring diagram for anyone that want to try this. Here's the pull request: https://github.com/adafruit/Adafruit-PN532/pull/82

**Comment by Oliv4945** [comment]
I am closing it as @Udinic implementation in #82 does the job and my PR needs work to be rebased

**Pull request closed without merging**
